"""
expand_query_intent_data_with_claude.py . RUN THIS
ON YOUR OWN MACHINE with your own Anthropic API key.

    (PowerShell) $env:ANTHROPIC_API_KEY="sk-ant-..."
    pip install anthropic
    python -m src.data.expand_query_intent_data_with_claude --per-class 40

Why this exists: query_intent_examples.py's 200 examples were authored
directly during this project's development, not generated by a live LLM
call -- see that module's docstring for why. This script is the piece that
actually satisfies the SearchLens spec's "generate synthetic training data
with Claude API if needed" line literally: it calls the real Claude API to
generate NEW example queries per intent class, in a genuinely different
voice/style/topic mix than the hand-authored seed set, and appends them to
data/raw/query_intent_train.csv. It never touches query_intent_val.csv, so
val stays a clean holdout the model-generated data can't leak into.

This needs the `anthropic` package and a real API key -- neither is
available/appropriate to run from the sandbox, so this was written but not
executed there. Report whatever it actually generates when you run it.
"""
import argparse
import csv
import json
import os
from pathlib import Path

RAW_DIR = Path(__file__).resolve().parents[2] / "data" / "raw"

INTENT_DESCRIPTIONS = {
    "factual": "has one correct, verifiable, factual answer (e.g. dates, "
    "measurements, names, definitions)",
    "navigational": "the user is trying to reach one specific, known "
    "website or page (e.g. a brand name plus 'login', 'homepage', "
    "'customer service')",
    "exploratory": "the user wants a broad, general understanding of a "
    "topic, not one fact (e.g. 'explain X', 'tell me about Y')",
    "comparison": "the user is weighing two or more named options against "
    "each other (e.g. 'X vs Y', 'difference between X and Y')",
    "how-to": "the user wants step-by-step instructions to accomplish a "
    "task (e.g. 'how to X')",
}


def build_prompt(intent: str, n: int, existing_examples: list) -> str:
    existing_sample = "\n".join(f"- {q}" for q in existing_examples[:10])
    return f"""Generate {n} realistic search-engine queries for the "{intent}" intent class.

Definition of this class: {INTENT_DESCRIPTIONS[intent]}

Here are 10 existing examples of this class (for calibration -- do NOT repeat these, write NEW ones covering different topics/phrasing/vocabulary):
{existing_sample}

IMPORTANT -- the existing examples above mostly share one sentence
structure (e.g. always "X vs Y" / "difference between X and Y" for
comparison, or always starting with "how to X" for how-to). A classifier
trained only on that one structure per class learns to recognize the
TEMPLATE, not the actual intent, and fails on real queries phrased
differently. Your job is specifically to break that pattern:
- Vary SENTENCE STRUCTURE, not just topic. For every ~4 examples you write,
  include at least one that expresses the same intent with a genuinely
  different phrasing/structure than the examples above (e.g. for
  comparison: "should i get x or y", "is x better than y", "which is
  worth it, x or y", "x or y for beginners" -- not just "x vs y"; for
  how-to: "how do i x", "what's the best way to x", "steps to x", "x
  without professional help" -- not just "how to x").
- Vary formality and length too (some short/informal, some longer/precise).

Requirements:
- Return ONLY a JSON array of {n} lowercase query strings, nothing else.
- Cover varied topics (don't cluster on one subject area).
- Cover varied sentence structures per the instruction above -- this
  matters more than topic variety for this dataset.
- Keep each query a realistic length (2-12 words), like a real search query.
"""


def generate_for_intent(client, model: str, intent: str, n: int, existing_examples: list) -> list:
    prompt = build_prompt(intent, n, existing_examples)
    response = client.messages.create(
        model=model,
        max_tokens=1024,
        messages=[{"role": "user", "content": prompt}],
    )
    text = response.content[0].text.strip()
    # Models sometimes wrap JSON in a code fence despite instructions -- strip it.
    if text.startswith("```"):
        text = text.strip("`")
        if "\n" in text:
            text = text.split("\n", 1)[1]
        if text.lower().startswith("json"):
            text = text[len("json"):]
    queries = json.loads(text)
    if not isinstance(queries, list):
        raise ValueError(f"Expected a JSON array for intent={intent}, got: {type(queries)}")
    return [str(q).strip().lower() for q in queries if str(q).strip()]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--per-class", type=int, default=40, help="How many NEW examples to generate per intent class."
    )
    parser.add_argument("--model", type=str, default="claude-sonnet-4-5-20250929")
    args = parser.parse_args()

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        raise SystemExit("ANTHROPIC_API_KEY is not set. Set it in your environment before running this script.")

    import anthropic
    from src.data.query_intent_examples import INTENT_EXAMPLES

    client = anthropic.Anthropic(api_key=api_key)

    train_path = RAW_DIR / "query_intent_train.csv"
    if not train_path.exists():
        raise SystemExit(
            f"{train_path} not found. Run `python -m src.data.generate_query_intent_data` first."
        )

    new_rows = []
    for intent, existing_examples in INTENT_EXAMPLES.items():
        print(f"Generating {args.per_class} new '{intent}' examples via Claude API...")
        new_queries = generate_for_intent(client, args.model, intent, args.per_class, existing_examples)
        print(f"  Got {len(new_queries)} queries.")
        new_rows.extend((q, intent) for q in new_queries)

    with open(train_path, "a", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerows(new_rows)

    print(f"\nAppended {len(new_rows)} new rows to {train_path}.")
    print("data/raw/query_intent_val.csv was NOT touched -- it stays a clean holdout.")


if __name__ == "__main__":
    main()